### ISSUE TITLE
'npm run build' en mode 'static' donne une erreur 404

### ISSUE THREAD

**Issue by alexisflesch** [lovasoa/sanipasse#106]
Bonjour,

J'essaye de déployer sanipasse sur mon site web sur lequel je ne dispose pas de node. Après avoir cloné sanipasse puis fait "npm install", j'ai tenté : 
`npm run build`
puis j'ai uploadé le contenu du dossier build/ sur mon serveur. Le résultat est ici : 
https://sani.alexisfles.ch/

Cependant, j'ai une erreur dans la console : 
```
service-worker.js:35 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://sani.alexisfles.ch/import/video","status":404}]
    at PrecacheStrategy._handleInstall (https://sani.alexisfles.ch/service-worker.js:1261:13)
    at async PrecacheStrategy._handle (https://sani.alexisfles.ch/service-worker.js:1230:14)
    at async PrecacheStrategy._getResponse (https://sani.alexisfles.ch/service-worker.js:554:18)
```

Même si le site semble fonctionner, je ne peux pas accéder aux pages directement, par exemple : 
https://sani.alexisfles.ch/apropos

Cela me gêne car j'aimerais utiliser l'API.

Cependant, quand je test en local tout fonctionne avec 
`npm run dev`

J'imagine que j'ai mal configuré quelque chose mais je ne sais pas quoi et mes recherches n'ont rien donné.

**Comment by lovasoa** [comment]
> sur mon site web sur lequel je ne dispose pas de node

Le problème est ici. Vous devez soit installer et configurer l'application avec node soit utiliser un conteneur docker, ce que je conseille. 

Puisqu'il ne s'agit pas d'un bug, je vais fermer cette issue. Mais si vous avez besoin de conseil, n'hésitez pas à me contacter sur contact@ophir.dev
