### ISSUE TITLE
"Installer" avec Firefox Android ne fonctionne pas

### ISSUE THREAD

**Issue by hellpe** [lovasoa/sanipasse#11]
En ouvrant Sanipasse dans Firefox Android, si je clique sur "Installer" dans le menu de l'application, le menu se ferme et rien ne se passe.

Il s'agit peut-être d'un bug de Firefox, mais étant donné que sur les autres sites que j'ai pu essayer, le libellé du menu devient "Ajouter à l'écran d'accueil" au lieu d'"Installer", je ne suis pas arrivé à reproduire ce comportement.

**Comment by lovasoa** [comment]
Bonjour,

 Je viens de retester tout le processus d'installation dans firefox nightly pour android  91.0a1 (Build #2015818443)
AC: 91.0.20210625143048, 6dc0ca5c14
GV: 91.0a1-20210625093436
AS: 79.0.0

  Tout fonctionne correctement. De même avec google chrome. Votre problème est probablement un bug dans firefox, je vous conseille de le rapporter à mozille.

![photo5384559306420105762](https://user-images.githubusercontent.com/552629/123511551-2b91cc80-d682-11eb-95a5-284826853e6f.jpg)
![photo5384559306420105761](https://user-images.githubusercontent.com/552629/123511553-2c2a6300-d682-11eb-9108-e8b34921c1e4.jpg)
![photo5384559306420105760](https://user-images.githubusercontent.com/552629/123511554-2c2a6300-d682-11eb-9ddd-9de05f83bea4.jpg)
![photo5384559306420105759](https://user-images.githubusercontent.com/552629/123511556-2cc2f980-d682-11eb-92b6-ea511f6ac707.jpg)
![photo5384559306420105758](https://user-images.githubusercontent.com/552629/123511557-2d5b9000-d682-11eb-9ab5-066e585ea59d.jpg)

**Comment by lovasoa** [comment]
> Il s'agit peut-être d'un bug de Firefox, mais étant donné que sur les autres sites que j'ai pu essayer, le libellé du menu devient "Ajouter à l'écran d'accueil" au lieu d'"Installer", je ne suis pas arrivé à reproduire ce comportement.

Si vous voulez tester une autre webapp installable, vous pouvez essayer par exemple google news: https://news.google.com

**Comment by hellpe** [comment]
> 
> 
> > Il s'agit peut-être d'un bug de Firefox, mais étant donné que sur les autres sites que j'ai pu essayer, le libellé du menu devient "Ajouter à l'écran d'accueil" au lieu d'"Installer", je ne suis pas arrivé à reproduire ce comportement.
> 
> Si vous voulez tester une autre webapp installable, vous pouvez essayer par exemple google news: https://news.google.com

Cependant, lorsque l'application Google Actualités est déjà installée sur le téléphone (via le Play Store), l'option "Installer" devient "Ouvrir dans une application". J'ai cependant pu tester sur [airhorner.com](airhorner.com) et constater que le problème se reproduit. J'ai donc remonté le bug en amont [sur le GitHub de Firefox Mobile](https://github.com/mozilla-mobile/fenix/issues/20191).
