### ISSUE TITLE
Internal Server Error: cbor.decodeFirst is not a function

### ISSUE THREAD

**Issue by d-faure** [lovasoa/sanipasse#13]
à l'envoi d'un certificat UE reconnu

**Comment by lovasoa** [comment]
Bonjour,
  Merci de vous intéresser à sanipasse.
  Serait-il possible d'avoir plus d'informations ? Une liste d'étape qui permet de reproduire le bug, ainsi que (si possible), le certificat qui cause l'erreur ?

**Comment by d-faure** [comment]
Dans un onglet du navigateur (firefox)
1. Création d'un event pour le lendemain
2. Déclaration de soi dans la liste de participant
3. Copier de l'URL participant

Dans un autre onglet:
3. Ouverture de l'URL participant
4. Choix scan d'un certificat
5. Scan d'un certificat UE tel qu'émis par ameli à ce jour (QR-Code)
=> erreur et pas de validation

Même manip en fournissant le scancode 2D-DOC => OK

**Comment by lovasoa** [comment]
Meri ! Je peux reproduire l'erreur
