### ISSUE TITLE
Ajout du support des liens "walletdcc" de TousAntiCovid et des QR codes associés

### ISSUE THREAD

**Issue by d-faure** [lovasoa/sanipasse#14]
Cf. #13 pour la manipulation.
Le QR code du lien TousAntiCovid, _tel que donné dans la version UE des certificats Covid_, n'est pas reconnu

**Comment by lovasoa** [comment]
Est-ce que vous pourriez détailler votre problème ? 
Comment reproduire cette erreur ? D'où vient ce QR code? Pourriez-vous en donner un exemple ? (vous pouvez me l'envoyer sur contact at ophir point dev si vous ne voulez pas le poster ici)

**Comment by d-faure** [comment]
L'autre QR Code du certificat covid UE (censé permettre son ajout dans _TousAntiCovid_), n'est simplement pas reconnu par l'option de scan de certificat (contrairement à la version précédente).

**Comment by lovasoa** [comment]
Je pense que j'ai compris ce dont vous parliez.

Vous voudriez que sanipasse puisse sanner les liens comme: (avec mon certificat)

```
https://bonjour.tousanticovid.gouv.fr/app/walletdcc#HC1:6BFOXN%25TSMAHN-H6SKJPT.-7G2TZ978S8SFBXEJW.TFJTXG41UQR$TTSJBQO7C8AN9I6T5XH-G2%25E3EV4*2D5GPB+2SEB7:I/2DY735LBJU0:HNIYNTAFPLNPHNJYVW250$40ATPHN7Y47%25S%25*48YIZ73423ZQT-EJEG3XW43%252..P*PP:+P*.1D9R+Q6646S%250.LJB/S7-SN2H%20N37J3JFTULJ5CB8X2+36D-I/2DBAJDAJCNB-43%20X45X2DPF1BJ3X8I235AL5:4A93JKBIFT*EJFG3SZ4RZ4E%255MK97R9NQU8WUT+UVY9C9Q5:UUKU-O1B/9MM52718AL3*I2$8QJAZGA+1V2:U2E4:47%25N3*4RO47:8V65TFYS8BO+%20F/+B2MEF+DHRBPA3%25Y7.%20S9*2GOBZT3JY47LE5-PO3WHYEP0WR/IBKG::6KYTM1QZHVW7GVSCNZTA00XN850
``` 

et les QR codes qui contiennent ce type de lien, comme celui qui est en bas à gauche dans les certificats ameli.

Je note la demande et je marque cette issue comme "demande d'amélioration"

**Comment by d-faure** [comment]
C'est cela même.
