### ISSUE TITLE
erreur 500: HTMLElement is not defined

### ISSUE THREAD

**Issue by Trickscenique** [lovasoa/sanipasse#145]
Merci de bien vouloir décrire ici votre appareil, votre navigateur, et les circonstances d'apparition du bug.

## Informations techniques

```
{
    "name": "ReferenceError",
    "message": "HTMLElement is not defined",
    "stack": "ReferenceError: HTMLElement is not defined"
}
```

**Comment by Trickscenique** [comment]
Surement un problème d'ordre de chargement javascript, car après réactualisation cela fonctionne correctement.

**Comment by lovasoa** [comment]
Je peux reproduire l'erreur sur https://sanipasse.fr/french-health-pass et https://sanipasse.fr/borne/statistiques

Elle vient d'une dépendance qui a été mise à jour: https://github.com/bestguy/sveltestrap/issues/414

**Comment by lovasoa** [comment]
Merci d'avoir rapporté l'erreur !

**Comment by Trickscenique** [comment]
Au passage (ce n'est peu être pas l'endroit pour discuter de cela) Mais aurais-tu des retours d'une mise en production sur un événement réel ?

**Comment by lovasoa** [comment]
Oui, sanipasse a déjà été utilisé dans des centaines d'événements, publics ou privés, partout en France, depuis sa création. Je travaille aussi avec des entreprises qui utilisent sanipasse dans un cadre professionnel, et qui utilisent ou distribuent sanipasse borne. Si vous avez besoin d'un contrat de support professionnel pour sanipasse, n'hésitez pas à me contacter sur contact@ophir.dev
