### ISSUE TITLE
Pass 2DOC renvoie valide avec un seul vaccin PFIZER

### ISSUE THREAD

**Issue by SjarletK** [lovasoa/sanipasse#147]
Bonjour,

J'ai un pass sanitaire qui est marqué comme valide avec votre outil, alors qu'il ne contient qu'un seul vaccin (datant du 10 mai 2021) (et n'a pas eu le COVID19)

Je veux bien vous passer le code pour que vous testiez, mais pas en public (données de la personne)

Merci

**Comment by lovasoa** [comment]
Quel est le résultat du scan de ce code sur TousAntiCovid-Vérif ?

C'est normal qu'un passe de première dose soit valide si vous avez moins de 65 ans, normalement...

Si le passe est invalide sur l'application du gouvernement mais valide sur sanipasse, vous pouvez me l'envoyer sur contact@ophir.dev et je l'inspecterai

**Comment by lovasoa** [comment]
Excusez-moi, il n'est pas normal qu'un passe avec une seule dose de PFIZER soit valide. Je viens de corriger le problème.

**Comment by SjarletK** [comment]
le résultat du scan est le suivant:
![image](https://user-images.githubusercontent.com/85485907/148040927-1305c49d-86a8-4dc1-842e-05a27fb57f46.png)

Je vous envoie le code DDOC

**Comment by SjarletK** [comment]
> Excusez-moi, il n'est pas normal qu'un passe avec une seule dose de PFIZER soit valide. Je viens de corriger le problème.

Merci beaucoup!

**Comment by lovasoa** [comment]
Je viens de publier la correction, elle sera en ligne dans quelques minutes

**Comment by SjarletK** [comment]
vous voulez que je vous envoie le code DDOC quand même ou vous avez ce qu'il faut?

**Comment by lovasoa** [comment]
Vous pouvez m'envoyer le 2DDOC si vous voyez que le problème persiste, mais normalement c'est corrigé. J'ai testé avec mon passe de première dose personnel:

![image](https://user-images.githubusercontent.com/552629/148041865-b9975bc8-3fa6-478d-807e-22b4260e02a5.png)
