### ISSUE TITLE
Error: Function called outside component initialization

### ISSUE THREAD

**Issue by Ben-74** [lovasoa/sanipasse#185]
Merci de bien vouloir décrire ici votre appareil, votre navigateur, et les circonstances d'apparition du bug.

Sur plusieurs PC avec 2 modèles de webcams différentes et même sur smartphone Samsung. L'image webcam ne fonctionne plus alors que c'est OK avec d'autres logiciels

**Comment by lovasoa** [comment]
Je viens de corriger le problème, le déploiement est en cours. Désolé du dysfonctionnement !

**Comment by Ben-74** [comment]
Merci 👏🏻
