### ISSUE TITLE
Enregistrement du certificat

### ISSUE THREAD

**Issue by gromez** [lovasoa/sanipasse#2]
Tout d'abord déjà, merci pour l'application :+1: 

Je me demandais si il était prévu d'avoir une fonction d'enregistrement (en local bien sûr) d'un certificat après un scan car pour le moment ce n'est que de la vérification/consultation.

**Comment by lovasoa** [comment]
Bonjour !
  Oui, c'est une bonne idée.
  On pourrait utiliser [localForage](https://localforage.github.io/localForage/#localforage) pour le stockage, et zxing pour la génération de datamatrix.  Est-ce que ça vous intéresserait d'implémenter cette fonctionnalité ?

**Comment by gromez** [comment]
Alors je ne connais pas spécialement SvelteKit mais je peux regarder ce que je peux faire.
