### ISSUE TITLE
2D-DOC et QR Code

### ISSUE THREAD

**Issue by adam314315** [lovasoa/sanipasse#26]
Bonjour,

Sanipasse gère-t-il également les QR codes car il semblerait que ce soit le nouveau format qui sera utilisé à l'échelle européenne et remplacera le 2D-DOC.
Sur le site de test sanipasse.fr, il semble que les QR code ne sont pas reconnus (tester en essayant d'utiliser la caméra de l'appareil avec un QR code papier).

**Comment by lovasoa** [comment]
Si ! les QR codes des passes sanitaires européens sont reconnus.

**Comment by adam314315** [comment]
Bonne nouvelle. Cependant je n'ai pas réussi à le faire fonctionner avec les QR test européen :  https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/FR 
(exemple : https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/FR/png/DGC_QrCode_00001.png)

L'erreur ci-dessous est affichée 

![Screenshot_466](https://user-images.githubusercontent.com/35598037/125991897-e247c397-ee70-4714-a640-b2f3dbc0d810.png)

**Comment by gilbsgilbs** [comment]
Les DCC du repo de l'UE sont signés avec des clés de test, ils ne sont pas authentiques. C'est donc le comportement attendu de les refuser.

**Comment by lovasoa** [comment]
Oui, notre message d'erreur est mauvais, on devrait afficher un message du type 

> Ce certificat n'est pas signé avec l'une des clefs numériques officiellement approuvées en France.

@adam314315 : Vous seriez intéressé de faire une petite PR ? C'est juste quelques lignes.
