### ISSUE TITLE
when a guest RSVP's to an event, its name should not be fully seen

### ISSUE THREAD

**Issue by laurentperez** [lovasoa/sanipasse#28]
Hi

Use case :  

- set an event with https://sanipasse.fr/events
- add a guest with name Test ABCD
- send the link to the guest
- guest uploads a valid pdf

My "problem" : the guest is listed as accepted, but its name does not match Test ABCD (of course), so the UI will display its real name, with status accepted but was not invited

This is a special case where I do set an event at a place, but I do not want to know the real name of some of my guests

hint : no it's not a partouze 🐖

**Comment by lovasoa** [comment]
Bonjour,
  Ce que vous décrivez est le fonctionnement normal de sanipasse. Le lien d'invitation est commun à tous les invités, et l'organisateur voit ensuite dans son interface trois catégories d'invité différentes: invité et non validé, invité et validé, non invité et validé. Cela simplifie la vie des organisateurs de grands événements, qui n'ont pas à ajouter manuellement à l'avance le nom de tous les invités.
  
  Si je comprends bien le fonctionnement que vous désireriez, c'est qu'il y ait un lien par invité, qui ne contienne pas son nom réel, et qui puisse être validé par l'invité de son côté. Je ne suis pas sûr de la pertinence de ce mode de fonctionnement: les invités pourraient simplement télécharger sur internet ou demander à un ami le certificat de vaccination de quelqu'un d'autre, et apparaître comme validé sur l'interface de l'organisateur.

**Comment by laurentperez** [comment]
Oui, je comprends que l'abus de la part du guest est possible, même si il est bien indiqué de ne jamais partager son QR code. Il peut toujours le "louer" à un tiers, ou forger un vrai faux avec complicité de médecin/autre.

C'est un use cas très limite, où clairement je ne veux pas connaître l'identité de la personne. Mais elle souhaite venir à l'event, et me prouver son vaccin.

L'alternative que j'ai trouvée pour le moment est de lui scanner son QR à l'entrée de l’événement, mais de physiquement masquer avec un post-it les champs qui révèlent nom prénom et date de naissance. Ou de forker pour masquer ces div.

**Comment by lovasoa** [comment]
Si vous faites confiance à cette personne quand elle vous dit que c'est bien son passe à elle qu'elle a scanné, pourquoi ne pas lui faire confiance directement quand elle vous dit qu'elle est vaccinée ?

**Comment by laurentperez** [comment]
Disons que c'est pas tant un sujet confiance - je ne connais déjà pas la personne - mais davantage anonymat. Si doute, lui faire scanner devant moi son QR, je ne veux juste pas connaître son identité.

On est d'accord qu'elle peut me présenter un vrai faux QR ou celui d'un tiers, mais le % de chance qu'elle aie obtenu ça est faible. Elle aura plus de chances d'être réellement vax et dans ce cas, je ne veux juste pas connaître son identité ; elle ne connaît pas non plus la mienne, et dans le sens inverse je peux aussi lui montrer le QR en masquant mon identité.

On peut clore ;) J'ai ouvert en tant que Issue, mais c'est plus une discussion qu'un bug. C'est une zone grise claire, il ne se passe néanmoins rien d'illégal lors de l'event.

**Comment by lovasoa** [comment]
Très bien, je ferme l'issue.
