### ISSUE TITLE
Branche borne

### ISSUE THREAD

**Issue by Shotman** [lovasoa/sanipasse#29]
Cette branche est-elle terminée ? Je viens de cloner le repo pour tester cette branche afin de proposer de mettre sanipasse à l'entrée d'un établissement pour automatiser un minimum le processus mais il semble que le scan video n'est pas fonctionnel sur cette route ?

**Comment by lovasoa** [comment]
Bonjour,
  Je travaille sur le développement d'une borne sanipasse en partenariat avec une entreprise de matériel. Vous pouvez suivre les articles sur sanipasse, je communiquerai bientôt sur le sujet.
   Le code sur cette branche est déjà fonctionnel: il ne fonctionne pas en vidéo, mais avec un scanner de QR code physique. Je vous invite à me contacter sur `contact@ophir.dev` si vous avez des besoins particuliers dont vous aimeriez discuter.

**Comment by hgshoggins** [comment]
Bonjour, 
Peut-on envisager un fonctionnement "hybride", à mi-chemin entre la borne et l'appli web, afin de soumettre à l'appli (par une API quelconque) le contenu du QRCode, et d'obtenir une réponse ?

**Comment by lovasoa** [comment]
@hgshoggins : j'ai créé une issue séparée pour discuter de cela

**Comment by lovasoa** [comment]
Je viens de publier officiellement la nouvelle version de sanipasse, qui contient la fonctionnalité de **borne sanipasse**.

https://sanipasse.fr/borne/config
