### ISSUE TITLE
Erreur à la soumission d'un certificat

### ISSUE THREAD

**Issue by chimons** [lovasoa/sanipasse#3]
Bonjour, 
J'obtiens l'erreur suivante à la soumission d'un certificat : 
⚠️ Erreur
Unexpected end of JSON input

![image](https://user-images.githubusercontent.com/4195659/118947178-6011ba80-b957-11eb-82d7-1db1498047aa.png)

Néanmoins, le certificat est bien envoyé et traité par le serveur puisqu'il apparait ensuite dans la liste des participants à l'évènement. 

Testé depuis Vivaldi 3.3.2022.47 sur Windows 10

Etapes pour reproduire : 
- Créer un évènement
- Accèder à la page d'imort d'un certificat par QR Code
- Scanner un certificat de vaccination
- Cliquer sur "Envoyer mon certificat"

**Comment by lovasoa** [comment]
Merci d'avoir signalé ce bug, @chimons !

### Interface corrigée

<img width="514" alt="image" src="https://user-images.githubusercontent.com/552629/118967961-a5d87e00-b96b-11eb-935f-52065a5f74bf.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/552629/118967989-af61e600-b96b-11eb-97ba-6ad211746aa2.png">
