### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by MaximeP1** [lovasoa/sanipasse#32]
Bonjour, 

Dans le fichier [/src/routes/index.svelte](../blob/master/src/routes/index.svelte)

* Ligne 44 :  `Votre passe sanitaire est <a href="apropos#donnees">strictement privée</a>. Il ne sera`
-> Votre passe sanitaire est strictement **privé**. Il ne sera

**Comment by lovasoa** [comment]
Merci !
