### ISSUE TITLE
Legislation quant au remplacement de tous anti covid verif par sanipasse

### ISSUE THREAD

**Issue by egobiah** [lovasoa/sanipasse#33]
Bonjour,

J'essaye de trouver les textes de loi de la CNIL par rapport à l'utilisation de sanipasse mais le seul bout de texte que j'ai trouvé est :

`TousAntiCovid Verif est l’unique application autorisée en France pour effectuer le contrôle sanitaire. `

Trouvé dans le PDF "FAQ - Le « pass sanitaire » pour les professionnels" [FAQ - Le « pass sanitaire » pour les professionnels](https://www.gouvernement.fr/sites/default/files/cfiles/tac_faq_pro_02072021.pdf) disponible sur [https://www.gouvernement.fr/info-coronavirus/pass-sanitaire](https://www.gouvernement.fr/info-coronavirus/pass-sanitaire) 

Avez vous pris contact ou même eu des retours avec les organisations compétentes quant à l'autorisation d'utiliser l'application pour la vérification des pass sanitaire ?

**Comment by gilbsgilbs** [comment]
Voir aussi : https://www.legifrance.gouv.fr/loda/id/JORFTEXT000043575238

>  III.-La lecture des justificatifs par les personnes mentionnées au II est réalisée au moyen d'une application mobile dénommée “ TousAntiCovid Vérif ”, mise en œuvre par le ministre chargé de la santé (direction générale de la santé). Elle permet à ces personnes de lire les noms, prénoms et date de naissance de la personne concernée par le justificatif, ainsi qu'un résultat positif ou négatif de détention d'un justificatif conforme, établi conformément aux dispositions de l'article 2-2.

Mais pas de peine associée donc on s'en fiche ?

(IANAL)

**Comment by egobiah** [comment]
Je souhaite proposer la solution dans l'établissement ou je travail et n'étant pas le responsable moral de celui-ci je souhaite garantir aucun problème lie à l'utilisation de sanipasse (surtout un texte tout prêt en cas de contrôles par la police)

Je continu mes investigations et j'appellerai sûrement le numéro vert disponible pour les professionnels.

Je partagerai le résultat de ces recherches

**Comment by adam314315** [comment]
Salut,

Nous envisageons également de mettre en place la solution Sanipasse pour nos salariés et les visiteurs.
@egobiah : Avez-vous pu trouver quelques infos supplémentaires sur la réglementation ?

**Comment by egobiah** [comment]
Je viens d'appeler le numéro vert réservé au professionnel et la personne au téléphone était catégorique sur le fait uniquement TAC verif est autorisé. Je lui ai demandé le texte de loi et elle a demandé à son responsable qui m'as redirigée  vers la FAQ... Celui-ci m'as aussi indiqué que l'information va sûrement être inscrite dans les jours qui arrivent dans le texte de loi.

Pas plus d'avancement..

**Comment by lrq3000** [comment]
Je pense qu'il serait judicieux de considérer sanipasse plutôt comme une alternative à la version papier, mais à voir si légalement c'est acceptable ou si la version papier doit nécessairement être sur papier.

D'après [BFMtv](https://www.bfmtv.com/tech/papier-tous-anti-covid-pdf-simple-photo-comment-presenter-son-pass-sanitaire_AV-202106090156.html) dans un article publié le 09/06/2021 à 10:50:

> Le décret publié ce 7 juin précise par ailleurs que le QR Code peut être présenté “sur l'application mobile TousAntiCovid ou tout autre support numérique au choix de la personne concernée”. Autrement dit: une présentation du fichier PDF téléchargé sur Sidep ou Ameli peut suffire, au même titre qu’une simple capture d’écran, voire une photo du QR Code en question.

Si ce qu'écrit BFMtv est correct (et je ne suis pas un légaliste donc je ne peux vérifier ces propos), Sanipasse pourrait être utilisé en remplacement de TousAntiCovid pour présenter son pass sanitaire lors des contrôles.

À noter par ailleurs que [certaines personnes](https://www.nextinpact.com/lebrief/47209/le-pass-sanitaire-et-tousanticovid-signal-se-preparent) se plaignent que le logiciel TousAntiCovid ne fonctionne pas sur leurs téléphones, ce qui est une raison supplémentaire pour justifier l'existence d'alternatives comme Sanipasse.

**Comment by lovasoa** [comment]
Bonjour,
  Je ferme cette "issue" parce que ce n'est pas vraiment un bug avec sanipasse, mais la discussion reste ouverte ci-dessous.

**Comment by lovasoa** [comment]
Des nouvelles du journal officiel:

https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000043915443

La lecture des justificatifs par les personnes et services mentionnés au II peut être réalisée au moyen d'une application mobile dénommée “ TousAntiCovid Vérif ”, mise en œuvre par le ministre chargé de la santé (direction générale de la santé), ou de tout autre dispositif de lecture répondant à des conditions fixées par un arrêté des ministres chargés de la santé et du numérique. Les personnes mentionnées aux 1° et 3° utilisant ces derniers dispositifs en informent le préfet de département.
