### ISSUE TITLE
Calcul nombre de jours écoulés

### ISSUE THREAD

**Issue by adam314315** [lovasoa/sanipasse#34]
Bonjour,

Lors de l'import d'un certificat, le résultat obtenu est invalide car le test aurait plus de 6 mois sauf que le nombre de jours calculés 53 910 est erroné. 
Ci-dessous la photo des détails obtenus. Les détails semblent correctent mais le calcul du nombre de jours écoulés et l'interprétation en statut invalide semblent incorrects.

![test](https://user-images.githubusercontent.com/35598037/127355410-92141c06-228d-49e0-a87e-f3013e1b4430.png)

**Comment by lovasoa** [comment]
@adam314315 : Est-ce que la date sur votre ordinateur est correcte ?

**Comment by adam314315** [comment]
Oui elle est correcte. J'ai obtenu exactement le même résultat à partir du PC et via le mobile en me connectant sur sanipasse.fr

**Comment by lovasoa** [comment]
Effectivement, il y a un bug !

**Comment by lovasoa** [comment]
Vous pouvez tester la correction ici:  https://deploy-preview-35--sanipasse.netlify.app/ 

Si tout va bien, je déploierai la version corrigée

**Comment by adam314315** [comment]
Oui c'est réglé à présent. Merci.
