### ISSUE TITLE
Code mode frontière?

### ISSUE THREAD

**Issue by lrq3000** [lovasoa/sanipasse#37]
L'application TousAntiCovid montre maintenant des informations supplémentaires en activant le "mode frontière". L'une de ces infos est un code en bas de page, qui ressemble à un hash:

![Screenshot_20210802_192403_fr gouv android stopcovid2](https://user-images.githubusercontent.com/1118942/127901318-0287ea5f-84ee-4955-9a21-9f099378fe38.jpg)

(J'ai caché certaines parties du code pour des raisons de confidentialité).

J'ai cherché dans les données brutes décodées par Sanipasse mais il n'y est pas.

D'où vient ce code et à quoi sert-il? Pourrait-il être rajouté dans Sanipasse au cas où celui-ci vient à être utilisé lors de vérifications?

**Comment by lovasoa** [comment]
Vous devriez pouvoir trouver ce à quoi correspond ce code dans les sources de l'application: https://gitlab.inria.fr/stopcovid19/stopcovid-android

**Comment by lovasoa** [comment]
I think it's the `sha256(concat(uppercase(countryCode), certificateIdentifier))` of the certificate:

https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/blob/master/stopcovid/src/main/java/com/lunabeestudio/stopcovid/fragment/FullscreenDccFragment.kt

https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/blob/master/stopcovid/src/main/java/com/lunabeestudio/stopcovid/model/WalletCertificate.kt#L365

https://gitlab.inria.fr/stopcovid19/dgca-app-core-android/-/blob/main/decoder/src/main/java/dgca/verifier/app/decoder/model/GreenCertificate.kt#L57

**Comment by lovasoa** [comment]
@lrq3000 : vous pourriez faire une petite PR pour ajouter cette info ? Ce serait dans https://github.com/lovasoa/sanipasse/blob/master/src/routes/_CertificateDGCDetails.svelte

vous avez accès au certificateIdentifier avec vaccine.ci ou test.ci

**Comment by lrq3000** [comment]
Bingo! C'est bien le hash SHA256 de la concatenation de `co` et `ci` :D Je viens de vérifier et ça match avec mes données!

Je vous remercie pour l'invitation à faire un PR mais je n'ai aucune expérience en Svelte et je ne suis pas un codeur JS :-/

**Comment by lovasoa** [comment]
@lrq3000 : done ✅

**Comment by lrq3000** [comment]
Merci beaucoup :D Je viens de tester, ça marche parfaitement, ça affiche bien le même code :-)
