### ISSUE TITLE
Mise à jour des certificats

### ISSUE THREAD

**Issue by RomainTT** [lovasoa/sanipasse#38]
Est-ce qu’il ne serait pas pertinent de récupérer les certificats dynamiquement ? Ou bien on peut se contenter de les mettre manuellement à jour…

Actuellement je vois que dans le [code](https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/blob/master/stopcovid/src/main/assets/Config/config.json) de l’INRIA il y a une nouvelle clé qui n’est pas dans ce [dépôt](https://github.com/lovasoa/sanipasse/blob/master/src/lib/2ddoc_check_signature.ts)

**Comment by lovasoa** [comment]
Bonjour,
  Les certificats sont déjà mis à jour automatiquement depuis le backend d'IN groupe, tout comme dans l'application TAC verif.

**Comment by lovasoa** [comment]
https://github.com/lovasoa/sanipasse/blob/master/fetch_certificates.js

https://github.com/lovasoa/sanipasse/blob/master/.github/workflows/renew_certificates.yml

**Comment by lovasoa** [comment]
Les clefs que vous regardiez sont celles de l'ancien format 2ddoc, qui n'est plus utilisé.

**Comment by RomainTT** [comment]
Autant pour moi ! Merci !
