### ISSUE TITLE
TypeError: Key is not of type 'CryptoKey'

### ISSUE THREAD

**Issue by Kaor** [lovasoa/sanipasse#46]
Bonjour,
j'essaie de mettre en place sanipasse pour nos évenements,
lors de la confirmation de présence sur un évenement j'ai une erreur : 
Internal Server Error : Key is not of type 'CryptoKey'
La machine tourne sous ubuntu 20.04 server et j'utilise votre container docker
Merci à vous pour votre aide et votre travail sur ce projet

**Comment by lovasoa** [comment]
Bonjour,
  Je suppose que vous utilisez l'image docker lovasoa/sanipasse ?
  Cette erreur a été corrigée, mais je n'ai pas encore publié la nouvelle version sur docker hub. Je fais ça au plus vite. 

  En attendant, vous pouvez construire vous-même l'image docker de la dernière version depuis les sources.

**Comment by Kaor** [comment]
Merci pour votre réponse,
je viens de construire l'image docker à partir des sources, l'erreur est reglée !
merci à vous

**Comment by lovasoa** [comment]
Je viens de publier `lovasoa/sanipasse:1.1.2`, qui contient le fix.
