### ISSUE TITLE
Mention "zero-covid" sur sanipasse.fr

### ISSUE THREAD

**Issue by UnSeulT** [lovasoa/sanipasse#49]
Merci pour cette alternative libre, auditable à tousanticovid-verif !

Je ne savais pas trop où te faire ce retour, je crée du coup une issue ici.
Concernant le site sanipass.fr où tu écris :
"Vous pouvez également Créer un événement, pour construire une liste d'invités zéro-COVID. "
Dans un soucis "d'exactitude sanitaire", la mention "zéro-COVD" n'est pas appropriée, c'est une liste d'invités aux certificats vérifiés, pas une "garantie" de zéro-COVID.

**Comment by lovasoa** [comment]
Je pense que le texte est assez clair sur la signification de *liste d'invités zéro-COVID*, d'ailleurs vous semblez l'avoir très bien compris :smiley: 
On pourrait aussi écrire liste d'invités ayant 0.001% de chances d'avoir le COVID, mais je trouve que c'est plus clair en arrondissant à 0...

**Comment by UnSeulT** [comment]
Je pensais surtout aux tests PCR dont la validité a été étendue à 72h, il semblerait qu'avec notamment le variant delta cela change la donne.
Pour être franc, je découvre sanipasse tardivement via la "news" de mai sur Linuxfr.org et je me suis laissé emporté à parcourir les (nombreux !) commentaires, cela a poussé mon côté tatillon à s'exprimer :)

Merci encore en tout cas pour ton initiative !

PS : oups, désolé pour la faute sur sanipassE.fr :)

**Comment by lovasoa** [comment]
Pas de problème ! Et si vous voulez jeter un oeil au code, vous êtes le bienvenu !
