### ISSUE TITLE
Rajouter de la doc sur comment tourner le containeur Docker

### ISSUE THREAD

**Issue by zoobab** [lovasoa/sanipasse#5]
Rajouter de la doc sur comment tourner le containeur Docker.

J'ai fait une version autobuildée ici sur le DockerHub:

```
$ docker run zoobab/sanipasse
Listening on port 3000
Executing (default): CREATE TABLE IF NOT EXISTS `events` (`public_code` VARCHAR(9) PRIMARY KEY, `private_code` VARCHAR(9), `na
me` VARCHAR(255), `date` DATETIME NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`events`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_events_1`)
Executing (default): CREATE UNIQUE INDEX `events_private_code` ON `events` (`private_code`)
Executing (default): CREATE TABLE IF NOT EXISTS `people` (`key` VARCHAR(255) NOT NULL, `eventPublicCode` VARCHAR(255) NOT NULL
 REFERENCES `events` (`public_code`) ON DELETE CASCADE ON UPDATE CASCADE, `validated` TINYINT(1) NOT NULL DEFAULT 0, `invited`
 TINYINT(1) NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`key`, `eventPublic
Code`));
Executing (default): PRAGMA INDEX_LIST(`people`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_people_1`)
```

Documenter l'option pour monter le /data ?

Et pointer son navigateur vers ```http://localhost:3000```.

**Comment by lovasoa** [comment]
Oui, très bonne idée ! 
La version "officielle" est ici : https://hub.docker.com/repository/docker/lovasoa/sanipasse

PR welcome :)

**Comment by seboss666** [comment]
Hello, je dirais même plus, même sans docker faudrait de la doc pour les utilisateurs du monde réel :D (parce qu'un npm build ça suffit pas à dire comment on l'héberge/fait tourner/persiste sur un serveur). Avec une vraie doc sur le conteneur docker on peut envisager de projeter ensuite dans un kube ;)

**Comment by lovasoa** [comment]
J'ai ajouté quelques informations dans le README 😃
