### ISSUE TITLE
Wrong Docker image URL

### ISSUE THREAD

**Issue by la-balisa** [lovasoa/sanipasse#56]
Hi ! I am just discovering you work.
I wanted to go to your DockerHub image, but the link is wrong.
It references https://hub.docker.com/repository/docker/lovasoa/sanipasse where it should be https://hub.docker.com/r/lovasoa/sanipasse , the first one being probably your dev access, as it required an authentication !
Thank you :)

**Comment by lovasoa** [comment]
fixed. Thanks for reporting !
