### ISSUE TITLE
sanipasse.db Docker 

### ISSUE THREAD

**Issue by sikkink** [lovasoa/sanipasse#58]
Bonjour,

Bravo pour ce travail hyper bien fait.
Juste un point, le docker "exite" immédiatement avec la commande : "docker run -d -p 80:3000 -v /your-volume/sanipasse/:/data/ --name sanipasse --rm lovasoa/sanipasse" car le fichier sanipasse.db n est plus accessible et pas encore crée dans le répertoire de l hote. Démarrer le docker sans "-v /your-volume/sanipasse/:/data/" puis "docker cp sanipasse:/data/sanipasse.db /your-volume/sanipasse" puis arrêter le docker supprimez le et redémarrez le avec la commande suggérée.
Bonne Soirée.

**Comment by n1b0r** [comment]
Bonjour,

Dans le monde de docker il y a (au moins) deux types de volume : les volumes et les bind mount.

Lors d'un bind mount (-v path:path) docker montera le dossier de l'hôte à l'endroit désiré. Si le dossier n'existe pas sur l'hôte, il sera créé automatiquement vide.

Avec un volume, (-v volume_name:path) docker crée un volume automatiquement et récupère les données issues du container.
  
Dans votre cas, vous voulez faire persister un dossier déja existant dans le container, il faut donc utilise le type volume : 
` docker run -d -p 80:3000 -v sanipasse_data:/data/ --name sanipasse --rm lovasoa/sanipasse`

C'est mon premier commentaire ici, j'espere que cela répond à votre question.

**Comment by lovasoa** [comment]
Bonjour, la commande donnée dans le README est correcte et fonctionne. Sanipasse crée automatiquement le fichier de base de données si il n'existe pas déjà. Par contre, il faut bien évidemment qu'il ait les droits nécessaires pour écrire dans le dossier que vous avez monté. Et attention à bien lire [la documentation de docker](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) si vous utilisez SELinux.

**Comment by lovasoa** [comment]
J'ai quand même mis à jour le README pour conseiller d'utiliser un volume. Ce sera plus simple, et évitera la confusion à l'avenir.
