### ISSUE TITLE
Liste noire de certificats

### ISSUE THREAD

**Issue by gilbsgilbs** [lovasoa/sanipasse#62]
L'application TousAntiCovid Verif a intégré dans sa version 1.8.0 un système de révocation de certificats.

[D'après le code source disponible pour l'application Android](https://gitlab.inria.fr/tousanticovid-verif/tousanticovid-verif-android/-/blob/b8a1a3b703b5b6421600f714e259e342b01e06b7/app/src/main/java/com/ingroupe/verify/anticovid/service/document/DocOfflineService.kt#L267), ça fonctionne de la même façon que dans TousAntiCovid : 
- DCC : sha256(country_code + uvci) cherché dans une liste de certificats révoqués
- 2D-DOC : sha256(2D-DOC sans signature) cherché dans une autre liste de certificats révoqués

Pour le moment ces deux listes sont vides : ils attendent probablement un feu vert de la CNIL ou quelque chose…

La liste peut se trouver facilement dans la liste de synchronisation qui est déjà utilisée par Sanipasse pour synchroniser les DSC (`specificValues->blacklist->blacklistDCC` et `specificValues->blacklist->blacklist2DDOC`). À noter qu'ils ont aussi ajouté le même système que dans sanipasse pour détecter les double utilisations d'un même passe, mais désactivé pour le moment (ça alimente juste les statistiques).

**Comment by lovasoa** [comment]
Merci de toutes ces infos! Je me marie ce weekend, je pourrai essayer d'implémenter ça la semaine prochaine. Sinon vous pouvez faire une PR, et je la mergerai le plus rapidement possible.

**Comment by gilbsgilbs** [comment]
Wow, félicitations ☺️ . Tous mes vœux de bonheur et vivent les (futurs) mariés !

Je vais voir si je peux y consacrer un peu de temps, mais zéro garantie que je pourrai m'en occuper avant la semaine prochaine…

**Comment by hgshoggins** [comment]
Testé aujourd'hui en scannant plusieurs fois le même passe valide, les stats de doublon ne sont pas alimentées. Peut-être parce que la conf. `json` indique encore `"duplicateActivate": false`.

**Comment by gilbsgilbs** [comment]
Exact, c'est désactivé pour le moment dans la config (https://portail.tacv.myservices-ingroupe.com/api/client/configuration/synchronisation/tacv). Activable à tout moment à distance donc. Lorsqu'ils l'activeront (s'ils le font), ça ressemblera à ça : 

**Pass blacklisté:**

![image](https://user-images.githubusercontent.com/3407667/130601116-a4cb4037-c036-4cb5-a6da-6e77277fd3cc.png)

**Pass "doublon" :**

![image](https://user-images.githubusercontent.com/3407667/130601201-c54817da-d14d-4db2-91c8-1708b83b3b3b.png)

**Comment by hgshoggins** [comment]
Le contenu de la config a été mis à jour : `blacklistDCC` contient des enregistrements.

**Comment by xavgra2** [comment]
Bonjour, 
Au vu des commentaires précédents, la source des données semble officielle et documentée.
Y a-t-il un enjeu technique qui empêche l'intégration des pass sanitaires révoqués car frauduleux ?

**Comment by lovasoa** [comment]
Non, il n'y a qu'à le faire. C'est une petite contribution simple à faire : il faut modifier le script fetch_certificates.js pour qu'il enregistre la liste des passes révoqués, et ajouter la vérification de la liste dans la fonction qui vérifie les passes. Est-ce que vous êtes intéressé?

**Comment by lovasoa** [comment]
Je l'ai implémenté dans https://github.com/lovasoa/sanipasse/commit/17abdcbc8ab77caded22f2bd47db4e7da4210688
