### ISSUE TITLE
firefox ubuntu not working

### ISSUE THREAD

**Issue by Lurikbolding** [lovasoa/sanipasse#63]
I test the app with firefox (66.0.3) on ubuntu.
The borne page or the test page did not ask to allow the camera.
So i can't start scanning qr code

i test the webcam with https://fr.webcamtests.com/ and it's working

how can i allow the webcam on sanipasse?

**Comment by lovasoa** [comment]
Bonjour,
  firefox 66 a été publié en 2019 et est déprécié.
  Je vais fermer cette issue en tant que duplicata de https://github.com/lovasoa/sanipasse/issues/43
