### ISSUE TITLE
Wrong decoding of certificate subject name

### ISSUE THREAD

**Issue by craftbyte** [lovasoa/sanipasse#72]
When decoding the signing certificate subject, backslashes are not taken into account. The organisation emettrice in the below example should say "NIJZ, National Institute of Public Health of Slovenia - NIJZ eHealth"

See example:
![image](https://user-images.githubusercontent.com/3154203/132122228-58ee4364-2934-4b88-927a-059aeb6a7cee.png)

**Comment by lovasoa** [comment]
Thanks for reporting the issue. It's fixed.
