### ISSUE TITLE
pass sanitaire validé avec 2 ième dose de vaccins de moins de 7 Jours

### ISSUE THREAD

**Issue by MickaelB** [lovasoa/sanipasse#73]
Bonjour,

Tout d'abord merci pour ce très bon boulot et cette outil très pratique.
Je viens de voir un petit soucis avec un invité qui aura son pass sanitaire "officiel" vendredi prochain:
schéma vaccinal complet + 7 jours.

Il a réussi a enregistré son QR code avec sanipass et de mon  côté il est validé.

Dans mon cas ce n'est pas important car l'événement à lieu samedi prochain.
Mais pour certains lieux public celà peut être ennuyeux:

d'après le site du gouvenement : https://www.gouvernement.fr/pass-sanitaire-toutes-les-reponses-a-vos-questions
1. La vaccination, à la condition que les personnes disposent d'un schéma vaccinal complet et du délai nécessaire après l’injection finale, soit :

    7 jours après la 2e injection pour les vaccins à double injection (Pfizer, Moderna, AstraZeneca) ;
    28 jours après l'injection pour les vaccins avec une seule injection (Johnson & Johnson) ;
    7 jours après l'injection pour les vaccins chez les personnes ayant eu un antécédent de Covid (1 seule injection).

Merci et bon courage pour la suite

**Comment by lovasoa** [comment]
Bonjour,
  Sanipasse valide les passes par rapport à la date de l'événement. C'est pour cela qu'il vous demande la date de l'événement. Si il ne fonctionnait pas comme cela, alors on pourrait par exemple valider sa participation avec un test qui est valable aujourd'hui mais ne le sera plus au moment de l'événement.
