### ISSUE TITLE
performance is not defined

### ISSUE THREAD

**Issue by PrestaSafe** [lovasoa/sanipasse#77]
Hi, once i've run `npm run dev` or `yarn run dev`

i've this issue:
```js
ReferenceError: performance is not defined
    at Object.handle (/Users/xxx/Documents/GitHub/sanipasse/src/hooks.ts:4:27)
    at respond (file:///Users/xxx/Documents/GitHub/sanipasse/node_modules/@sveltejs/kit/dist/ssr.js:1637:30)
    at Immediate.<anonymous> (file:///Users/xxx/Documents/GitHub/sanipasse/node_modules/@sveltejs/kit/dist/chunks/index.js:3484:28)
```

Thanks

**Comment by lovasoa** [comment]
Avez-vous suivi les instructions du README? Notamment, utilisez-vous une version de nodejs compatible?

**Comment by PrestaSafe** [comment]
Bonsoir, 

Oui tout à fait, node js est à jour ainsi que npm. 
Yarn vient également d’Être installé. 

Je suis sous un iMac 24 m1. Peut-être est-ce un soucis avec les processeur m1 ?

**Comment by lovasoa** [comment]
Que retourne `node --version` ?

**Comment by PrestaSafe** [comment]
`node --version -> v16.8.0` 
`npm --version -> 7.22.0`
`yarn --version -> 1.22.11`

**Comment by lovasoa** [comment]
Pourtant l'objet performance est défini globalement dans node depuis la version 16...

https://nodejs.org/docs/latest-v16.x/api/globals.html#globals_performance

**Comment by PrestaSafe** [comment]
Si je l'importe directement dans le `hooks.ts` ça fonctionne
`import {performance} from 'perf_hooks';`
