### ISSUE TITLE
[BORNE CONFIG] Faute de frappe 

### ISSUE THREAD

**Issue by LProgead** [lovasoa/sanipasse#86]
Bonjour,
Cette issue n'a rien de technique et serait même du _pinaillage_.

En effet, sur la [page de configuration de la borne](https://sanipasse.fr/borne/config), la catégorie d'interfaçage avec des services externes via HTTP affiche deux fois le même placeholder concernant le **valid-pass-endpoint**.

Comme je l'ai dit, cela n'empêche pas la borne de fonctionner, c'est une simple faute de frappe.

Bonne soirée,
LProgead :wave:

**Comment by lovasoa** [comment]
Merci! Est-ce que vous voulez le corriger, et ainsi devenir un contributeur de Sanipasse? 

Le changement est à faire ici : https://github.com/lovasoa/sanipasse/blob/master/src/routes/borne/_external_request_config.svelte#L85

**Comment by LProgead** [comment]
Bonjour,
J'aurais fais la contribution avec plaisir, mais je vois que vous l'avez déjà faite. 

Merci pour cette réactivité et c'est avec plaisir que je continuerai à essayer d'améliorer Sanipasse 😀

**Comment by lovasoa** [comment]
Merci à vous :slightly_smiling_face:
