### ISSUE TITLE
Comment ajouter le  clef d'API?

### ISSUE THREAD

**Issue by wrjcs** [lovasoa/sanipasse#89]
Bonjour
J'installe votre projet sur notre serveur, comment on peut ajouter le  clef d'API dans le serveur?

Merci d'avance.

**Comment by lovasoa** [comment]
Bonjour,
  Vous pouvez me contacter directement par mail sur "contact at ophir point dev" pour toute question concernant les clefs d'API. Si vous souhaitez intégrer sanipasse dans un logiciel propriétaire, vous aurez besoin d'une licence de ma part, que vous utilisiez sanipasse.fr ou un conteneur que vous hébergez vous-même.
  La version publique de sanipasse
